spring:
    datasource:
        url: "jdbc:mysql://localhost/nbtttracuudbs"
        username: nbtt2022
        password: nbtt2022
    sql:
        init:
            mode: always
            encoding: UTF-8

logging:
    level:
        root : info
    file:
        name : nbtt.log
    logback:
        rollingpolicy:
            max-file-size : 1MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true